namespace ExileCore.Shared.Enums;

public enum InventoryIndex
{
	None = 0,
	Helm = 1,
	Amulet = 2,
	Chest = 3,
	LWeapon = 4,
	RWeapon = 5,
	LWeaponSwap = 6,
	RWeaponSwap = 7,
	LRing = 8,
	RRing = 9,
	Gloves = 10,
	Belt = 11,
	Boots = 12,
	PlayerInventory = 13,
	Flask = 14,
	Trinket = 15,
	LWeaponSkin = 16,
	LWeaponEffect = 17,
	LWeaponAddedEffect = 18,
	RWeaponSkin = 19,
	RWeaponEffect = 20,
	RWeaponAddedEffect = 21,
	HelmSkin = 22,
	HelmAttachment1 = 23,
	BodySkin = 24,
	BodyAttachment = 25,
	GlovesSkin = 26,
	BootsSkin = 27,
	Footprints = 28,
	Apparition = 29,
	CharacterEffect = 30,
	Portrait = 31,
	PortraitFrame = 32,
	Pet1 = 33,
	Pet2 = 34,
	Portal = 35,
	HelmAttachment2 = 36,
	BloodCrucible = 52
}
