namespace ExileCore.Shared.Enums;

public enum MemoryProtectionType
{
	PAGE_NOACCESS = 1,
	PAGE_READONLY = 2,
	PAGE_READWRITE = 4,
	PAGE_WRITECOPY = 8,
	PAGE_EXECUTE = 0x10,
	PAGE_EXECUTE_READ = 0x20,
	PAGE_EXECUTE_READWRITE = 0x40,
	PAGE_EXECUTE_WRITECOPY = 0x80,
	PAGE_GUARD = 0x100,
	PAGE_NOCACHE = 0x200,
	PAGE_WRITECOMBINE = 0x400
}
